export class schoolfee{
    id:number=0;
    name:string = '';
    standard:string='';
    studentid:string ='';
    termfees:string='';
    busfee:string='';
    otherfee:string=''
    allotedfee:string =''; 
    balance:number = 0;
    balance2:number = 0;
    balance3:number = 0;
    triptype:string='';
    allotedbusfee:string='';
    boardingpoint:string='';
    selectedECA:string='';
    allotedECAfee:string='';
    type:string='';
    monthtype:string='';
    omonthtype:string='';
    termfee:number=0;
    monthfee:string='';
    omonthfee:string='';
    tpaiddate:string='';
    mpaiddate:string='';
    opaiddate:string='';
    tremarks:string='';
    mremarks:string='';
    oremarks:string='';
    totalTermFeesPaid: Number = 0;
    totalBusFeesPaid: Number = 0;
    totalOtherFeesPaid: Number = 0;
    billvalues:[]=[];
}
